### PR TITLE
rewrite it into one script

### PR DESCRIPTION
**Pull request by bebehei**
Bitte testen davor.

### CODE REVIEW

**Comment by Stunkymonkey** [comment]
Domain (the ending): stunkymonkey.de
Subdomain (ie. mail, www): asdf
Running OpenSSL...
Generating a 4096 bit RSA private key
....................................................................................................++
.......................................................................++
writing new private key to './certs/asdf.stunkymonkey.de/asdf_privatekey.pem'
./certs/asdf.stunkymonkey.de/asdf_privatekey.pem: No such file or directory
139911113324360:error:0E06D06C:configuration file routines:NCONF_get_string:no value:conf_lib.c:335:group=req name=default_bits
139911113324360:error:02001002:system library:fopen:No such file or directory:bss_file.c:398:fopen('./certs/asdf.stunkymonkey.de/asdf_privatekey.pem','w')
139911113324360:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:400:

Copy the following Certificate Request and paste into Startssl website to obtain a Certificate.

cat: ./certs/asdf.stunkymonkey.de/asdf_csr.pem: No such file or directory

```
    CSR: ./certs/asdf.stunkymonkey.de/asdf_csr.pem
```

Private Key: ./certs/asdf.stunkymonkey.de/asdf_privatekey.pem

Please paste your generated certificate here and press Ctrl+D after finishing:

test.sh: line 99: ./certs/asdf.stunkymonkey.de/asdf_startssl.pem: No such file or directory
Invalid option or option without parameter: -i
Usage:
-h      this help message
-k      Key File
-c      Certificate File
-i      Intermediate Certificate(s) File (one file, but may contain more than one intermediate certificate if necessary)
grep: ./certs/asdf.stunkymonkey.de/asdf_privatekey.pem: No such file or directory
/usr/local/bin/uberspace-prepare-certificate: line 86: [: -ge: unary operator expected
Mail was sent to harry-uhlbach@web.de

**Comment by bebehei** [comment]
Interessant ist die erste Zeile vom openSSL output:

>  ./certs/asdf.stunkymonkey.de/asdf_privatekey.pem: No such file or directory

Der Fehler tritt bei mir nicht auf. Hast du Schreibrechte in dem Ordner, wo du es ausführst?

**Comment by Stunkymonkey** [comment]
in dem ordner ja
`rwxr-xr-x 12 smonkey smonkey 4096  6. Aug 16:23 .`
`drwx------  2 smonkey smonkey 4096  6. Aug 16:23 asdf.stunkymonkey.de`
aber insgesamt ist der ordner "./asdf.stunkymonkey.de/" leer
`[smonkey@menkar asdf.stunkymonkey.de]$ ls -la`
`total 8`
`drwx------  2 smonkey smonkey 4096  6. Aug 16:23 .`
`drwxr-xr-x 12 smonkey smonkey 4096  6. Aug 16:23 ..`

**Comment by bebehei** [comment]
fuehrs nochmal aus. bei mir funktioniert das einwandfrei (mittlerweile auch auf dem uberspace)

**Pull request merged**
